# Generated by Django 4.2.5 on 2023-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pattern', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='pageextract',
            name='regex',
        ),
        migrations.AddField(
            model_name='pageextract',
            name='regex',
            field=models.ManyToManyField(to='ScrapeApp.regex'),
        ),
    ]
