# Generated by Django 4.2.5 on 2023-09-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrapeApp', '0002_regex_remove_pageextract_regex_pageextract_regex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regex',
            new_name='RegexModel',
        ),
    ]
